export const GROUP_ERRORS = {
  FORBIDDEN: 'FORBIDDEN',
  CONTACT_NOT_IN_GROUP: 'CONTACT_NOT_IN_GROUP',
  CONTACT_BLOCKED_ME: 'CONTACT_BLOCKED_ME',
  INVALID_CONTACT_ID: 'INVALID_CONTACT_ID',
  CONTACT_ALREADY_IN_GROUP: 'CONTACT_ALREADY_IN_GROUP',
  NOT_ADMIN: 'NOT_ADMIN',
  INVALID_GROUP_ID: 'INVALID_GROUP_ID',
  RECENT_LEAVE: 'RECENT_LEAVE',
}
