export enum ExposedFn {
  OnMessage = 'onMessage',
  OnAnyMessage = 'onAnyMessage',
  onAck = 'onAck',
  onParticipantsChanged = 'onParticipantsChanged',
  onStateChange = 'onStateChange',
  onIncomingCall = 'onIncomingCall',
  onAddedToGroup = 'onAddedToGroup',
  onInterfaceChange = 'onInterfaceChange',
  onStreamChange = 'onStreamChange',
  onFilePicThumb = 'onFilePicThumb',
  onChatState = 'onChatState',
  onUnreadMessage = 'onUnreadMessage',
  onPoll = 'onPoll',
}
