export { fileToBase64 } from './file-to-base64';
export { base64MimeType } from './base64-mimetype';
export { downloadFileToBase64 } from './download-file';
export { stickerSelect, resizeImg } from './select-sticker';
export { scrapeImg } from './scrape-img-qr';
export { scrapeLogin } from './scrape-login';
export { scrapeDesconnected } from './scrape-desconnect';
export { scrapeDeleteToken } from './scrape-deletetoken';
export { deleteFiles } from './delete-file';
export { callbackWile } from './callback-wile';
export { checkingCloses } from './closes-browser';
