export const GROUP_ERRORS = {
  BLOCKED_CONTACT: 'BLOCKED_CONTACT',
  FORBIDDEN: 'FORBIDDEN',
  CONTACT_NOT_IN_ADDRESS_BOOK: 'CONTACT_NOT_IN_ADDRESS_BOOK',
  CONTACT_NOT_IN_GROUP: 'CONTACT_NOT_IN_GROUP',
  CONTACT_BLOCKED_ME: 'CONTACT_BLOCKED_ME',
  INVALID_CONTACT_ID: 'INVALID_CONTACT_ID',
  CONTACT_ALREADY_IN_GROUP: 'CONTACT_ALREADY_IN_GROUP',
}
