export enum SocketState {
  // for state
  CONFLICT = 'CONFLICT',
  CONNECTED = 'CONNECTED',
  DEPRECATED_VERSION = 'DEPRECATED_VERSION',
  OPENING = 'OPENING',
  PAIRING = 'PAIRING',
  PROXYBLOCK = 'PROXYBLOCK',
  SMB_TOS_BLOCK = 'SMB_TOS_BLOCK',
  WITHOUT_INTERNET = 'WITHOUT INTERNET',
  TOS_BLOCK = 'TOS_BLOCK',
  UNLAUNCHED = 'UNLAUNCHED',
  UNPAIRED = 'UNPAIRED',
  UNPAIRED_IDLE = 'UNPAIRED_IDLE',
  // for stream
  DISCONNECTED = 'DISCONNECTED',
  RESUMING = 'RESUMING',
  SYNCING = 'SYNCING',
}
export enum SocketStream {
  CONNECTED = 'CONNECTED',
  DISCONNECTED = 'DISCONNECTED',
  RESUMING = 'RESUMING',
  SYNCING = 'SYNCING',
}
